name: Build Release
on:
  push:
    tags:
      - "*"
env:
  ProjectName: murmur
  Owner: hmbsbige # ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build
        run: |
          docker build --pull -t ghcr.io/${{ env.Owner }}/${{ env.ProjectName }}:${{ steps.tag.outputs.tag }} github.com/mumble-voip/mumble#v${{ steps.tag.outputs.tag }}

      - name: Push
        run: |
          docker push ghcr.io/${{ env.Owner }}/${{ env.ProjectName }}:${{ steps.tag.outputs.tag }}
