name: Docker
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  ProjectName: murmur
  Version: 1.4.230

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build
        run: docker build --pull -t ghcr.io/hmbsbige/${{ env.ProjectName }}:${{ env.Version }} github.com/mumble-voip/mumble#v${{ env.Version }}

      - name: Push
        run: |
          docker push ghcr.io/hmbsbige/${{ env.ProjectName }}:${{ env.Version }}
          docker push ghcr.io/hmbsbige/${{ env.ProjectName }}:latest
